### ISSUE TITLE
Increase code-coverage

### ISSUE THREAD

**Issue by iakunin** [iakunin/codexia-bot#10]
In the scope of this issue multiple pdd-puzzles should be added to decompose the whole scope of testing.

There are also useful resources concerning testing best-practices:
* https://www.freecodecamp.org/news/unit-testing-services-endpoints-and-repositories-in-spring-boot-4b7d9dc2b772/
* https://www.baeldung.com/integration-testing-in-spring
* https://www.baeldung.com/spring-boot-testing
* https://dzone.com/articles/unit-and-integration-tests-in-spring-boot-2
* https://phauer.com/2019/modern-best-practices-testing-java/
* https://phauer.com/2019/focus-integration-tests-mock-based-tests/
* https://martinfowler.com/articles/practical-test-pyramid.html
* https://tanzu.vmware.com/content/blog/what-is-a-unit-test-the-answer-might-surprise-you

**Comment by 0pdd** [comment]
@iakunin 11 puzzles [#54](https://github.com/iakunin/codexia-bot/issues/54), [#55](https://github.com/iakunin/codexia-bot/issues/55), [#56](https://github.com/iakunin/codexia-bot/issues/56), [#57](https://github.com/iakunin/codexia-bot/issues/57), [#58](https://github.com/iakunin/codexia-bot/issues/58), [#59](https://github.com/iakunin/codexia-bot/issues/59), [#60](https://github.com/iakunin/codexia-bot/issues/60), [#61](https://github.com/iakunin/codexia-bot/issues/61), [#62](https://github.com/iakunin/codexia-bot/issues/62), [#63](https://github.com/iakunin/codexia-bot/issues/63), [#64](https://github.com/iakunin/codexia-bot/issues/64) are still not solved.

**Comment by 0pdd** [comment]
@iakunin 10 puzzles [#54](https://github.com/iakunin/codexia-bot/issues/54), [#55](https://github.com/iakunin/codexia-bot/issues/55), [#56](https://github.com/iakunin/codexia-bot/issues/56), [#57](https://github.com/iakunin/codexia-bot/issues/57), [#58](https://github.com/iakunin/codexia-bot/issues/58), [#59](https://github.com/iakunin/codexia-bot/issues/59), [#60](https://github.com/iakunin/codexia-bot/issues/60), [#61](https://github.com/iakunin/codexia-bot/issues/61), [#62](https://github.com/iakunin/codexia-bot/issues/62), [#64](https://github.com/iakunin/codexia-bot/issues/64) are still not solved; solved: [#63](https://github.com/iakunin/codexia-bot/issues/63).

**Comment by 0pdd** [comment]
@iakunin 9 puzzles [#54](https://github.com/iakunin/codexia-bot/issues/54), [#55](https://github.com/iakunin/codexia-bot/issues/55), [#56](https://github.com/iakunin/codexia-bot/issues/56), [#57](https://github.com/iakunin/codexia-bot/issues/57), [#59](https://github.com/iakunin/codexia-bot/issues/59), [#60](https://github.com/iakunin/codexia-bot/issues/60), [#61](https://github.com/iakunin/codexia-bot/issues/61), [#62](https://github.com/iakunin/codexia-bot/issues/62), [#64](https://github.com/iakunin/codexia-bot/issues/64) are still not solved; solved: [#58](https://github.com/iakunin/codexia-bot/issues/58), [#63](https://github.com/iakunin/codexia-bot/issues/63).

**Comment by 0pdd** [comment]
@iakunin 8 puzzles [#54](https://github.com/iakunin/codexia-bot/issues/54), [#55](https://github.com/iakunin/codexia-bot/issues/55), [#56](https://github.com/iakunin/codexia-bot/issues/56), [#59](https://github.com/iakunin/codexia-bot/issues/59), [#60](https://github.com/iakunin/codexia-bot/issues/60), [#61](https://github.com/iakunin/codexia-bot/issues/61), [#62](https://github.com/iakunin/codexia-bot/issues/62), [#64](https://github.com/iakunin/codexia-bot/issues/64) are still not solved; solved: [#57](https://github.com/iakunin/codexia-bot/issues/57), [#58](https://github.com/iakunin/codexia-bot/issues/58), [#63](https://github.com/iakunin/codexia-bot/issues/63).

**Comment by 0pdd** [comment]
@iakunin 7 puzzles [#54](https://github.com/iakunin/codexia-bot/issues/54), [#55](https://github.com/iakunin/codexia-bot/issues/55), [#56](https://github.com/iakunin/codexia-bot/issues/56), [#59](https://github.com/iakunin/codexia-bot/issues/59), [#60](https://github.com/iakunin/codexia-bot/issues/60), [#61](https://github.com/iakunin/codexia-bot/issues/61), [#62](https://github.com/iakunin/codexia-bot/issues/62) are still not solved; solved: [#57](https://github.com/iakunin/codexia-bot/issues/57), [#58](https://github.com/iakunin/codexia-bot/issues/58), [#63](https://github.com/iakunin/codexia-bot/issues/63), [#64](https://github.com/iakunin/codexia-bot/issues/64).

**Comment by 0pdd** [comment]
@iakunin 6 puzzles [#54](https://github.com/iakunin/codexia-bot/issues/54), [#55](https://github.com/iakunin/codexia-bot/issues/55), [#56](https://github.com/iakunin/codexia-bot/issues/56), [#59](https://github.com/iakunin/codexia-bot/issues/59), [#60](https://github.com/iakunin/codexia-bot/issues/60), [#61](https://github.com/iakunin/codexia-bot/issues/61) are still not solved; solved: [#57](https://github.com/iakunin/codexia-bot/issues/57), [#58](https://github.com/iakunin/codexia-bot/issues/58), [#62](https://github.com/iakunin/codexia-bot/issues/62), [#63](https://github.com/iakunin/codexia-bot/issues/63), [#64](https://github.com/iakunin/codexia-bot/issues/64).

**Comment by 0pdd** [comment]
@iakunin 5 puzzles [#54](https://github.com/iakunin/codexia-bot/issues/54), [#55](https://github.com/iakunin/codexia-bot/issues/55), [#56](https://github.com/iakunin/codexia-bot/issues/56), [#59](https://github.com/iakunin/codexia-bot/issues/59), [#60](https://github.com/iakunin/codexia-bot/issues/60) are still not solved; solved: [#57](https://github.com/iakunin/codexia-bot/issues/57), [#58](https://github.com/iakunin/codexia-bot/issues/58), [#61](https://github.com/iakunin/codexia-bot/issues/61), [#62](https://github.com/iakunin/codexia-bot/issues/62), [#63](https://github.com/iakunin/codexia-bot/issues/63), [#64](https://github.com/iakunin/codexia-bot/issues/64).

**Comment by 0pdd** [comment]
@iakunin the puzzle [#54](https://github.com/iakunin/codexia-bot/issues/54) is still not solved; solved: [#55](https://github.com/iakunin/codexia-bot/issues/55), [#56](https://github.com/iakunin/codexia-bot/issues/56), [#57](https://github.com/iakunin/codexia-bot/issues/57), [#58](https://github.com/iakunin/codexia-bot/issues/58), [#59](https://github.com/iakunin/codexia-bot/issues/59), [#60](https://github.com/iakunin/codexia-bot/issues/60), [#61](https://github.com/iakunin/codexia-bot/issues/61), [#62](https://github.com/iakunin/codexia-bot/issues/62), [#63](https://github.com/iakunin/codexia-bot/issues/63), [#64](https://github.com/iakunin/codexia-bot/issues/64).
