### ISSUE TITLE
FallbackFromNull.java:8-9: replace this class with just...

### ISSUE THREAD

**Issue by 0pdd** [iakunin/codexia-bot#140]
The puzzle `136-5f5351ff` from #136 has to be resolved: 

https://github.com/iakunin/codexia-bot/blob/e4882869c1d02eb416279b2668356816562ebb91/src/main/java/dev/iakunin/codexiabot/bot/toosmall/FallbackFromNull.java#L8-L9

The puzzle was created by iakunin on 02-May-20. 

 role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by iakunin** [comment]
Is blocked by https://github.com/yegor256/cactoos/pull/1369

**Comment by 0pdd** [comment]
The puzzle `136-5f5351ff` has disappeared from the source code, that's why I closed this issue.
