### ISSUE TITLE
Use Streams in JpaRepositories

### ISSUE THREAD

**Issue by iakunin** [iakunin/codexia-bot#150]
* https://www.baeldung.com/spring-data-jpa-pagination-sorting
* https://www.baeldung.com/spring-data-jpa-query

----

- [x] All the `Set<>` and `List<>` must be replaced with `Stream<>`.
- [x] Also proper exception handling during stream processing is required (will be done in https://github.com/iakunin/codexia-bot/issues/93).

**Comment by 0pdd** [comment]
@iakunin the puzzle [#205](https://github.com/iakunin/codexia-bot/issues/205) is still not solved.

**Comment by 0pdd** [comment]
@iakunin the only puzzle [#205](https://github.com/iakunin/codexia-bot/issues/205) is solved here.
