### ISSUE TITLE
Implement `stars-up` bot

### ISSUE THREAD

**Issue by iakunin** [iakunin/codexia-bot#6]

**Comment by 0pdd** [comment]
@iakunin 9 puzzles [#19](https://github.com/iakunin/codexia-bot/issues/19), [#20](https://github.com/iakunin/codexia-bot/issues/20), [#21](https://github.com/iakunin/codexia-bot/issues/21), [#22](https://github.com/iakunin/codexia-bot/issues/22), [#23](https://github.com/iakunin/codexia-bot/issues/23), [#24](https://github.com/iakunin/codexia-bot/issues/24), [#25](https://github.com/iakunin/codexia-bot/issues/25), [#26](https://github.com/iakunin/codexia-bot/issues/26), [#27](https://github.com/iakunin/codexia-bot/issues/27) are still not solved.

**Comment by 0pdd** [comment]
@iakunin 11 puzzles [#20](https://github.com/iakunin/codexia-bot/issues/20), [#21](https://github.com/iakunin/codexia-bot/issues/21), [#22](https://github.com/iakunin/codexia-bot/issues/22), [#23](https://github.com/iakunin/codexia-bot/issues/23), [#24](https://github.com/iakunin/codexia-bot/issues/24), [#25](https://github.com/iakunin/codexia-bot/issues/25), [#26](https://github.com/iakunin/codexia-bot/issues/26), [#27](https://github.com/iakunin/codexia-bot/issues/27), [#39](https://github.com/iakunin/codexia-bot/issues/39), [#40](https://github.com/iakunin/codexia-bot/issues/40), [#41](https://github.com/iakunin/codexia-bot/issues/41) are still not solved; solved: [#19](https://github.com/iakunin/codexia-bot/issues/19).

**Comment by 0pdd** [comment]
@iakunin 9 puzzles [#20](https://github.com/iakunin/codexia-bot/issues/20), [#21](https://github.com/iakunin/codexia-bot/issues/21), [#22](https://github.com/iakunin/codexia-bot/issues/22), [#25](https://github.com/iakunin/codexia-bot/issues/25), [#26](https://github.com/iakunin/codexia-bot/issues/26), [#27](https://github.com/iakunin/codexia-bot/issues/27), [#39](https://github.com/iakunin/codexia-bot/issues/39), [#40](https://github.com/iakunin/codexia-bot/issues/40), [#41](https://github.com/iakunin/codexia-bot/issues/41) are still not solved; solved: [#19](https://github.com/iakunin/codexia-bot/issues/19), [#23](https://github.com/iakunin/codexia-bot/issues/23), [#24](https://github.com/iakunin/codexia-bot/issues/24).

**Comment by 0pdd** [comment]
@iakunin 8 puzzles [#20](https://github.com/iakunin/codexia-bot/issues/20), [#21](https://github.com/iakunin/codexia-bot/issues/21), [#22](https://github.com/iakunin/codexia-bot/issues/22), [#25](https://github.com/iakunin/codexia-bot/issues/25), [#27](https://github.com/iakunin/codexia-bot/issues/27), [#39](https://github.com/iakunin/codexia-bot/issues/39), [#40](https://github.com/iakunin/codexia-bot/issues/40), [#41](https://github.com/iakunin/codexia-bot/issues/41) are still not solved; solved: [#19](https://github.com/iakunin/codexia-bot/issues/19), [#23](https://github.com/iakunin/codexia-bot/issues/23), [#24](https://github.com/iakunin/codexia-bot/issues/24), [#26](https://github.com/iakunin/codexia-bot/issues/26).

**Comment by 0pdd** [comment]
@iakunin 7 puzzles [#20](https://github.com/iakunin/codexia-bot/issues/20), [#21](https://github.com/iakunin/codexia-bot/issues/21), [#22](https://github.com/iakunin/codexia-bot/issues/22), [#27](https://github.com/iakunin/codexia-bot/issues/27), [#39](https://github.com/iakunin/codexia-bot/issues/39), [#40](https://github.com/iakunin/codexia-bot/issues/40), [#41](https://github.com/iakunin/codexia-bot/issues/41) are still not solved; solved: [#19](https://github.com/iakunin/codexia-bot/issues/19), [#23](https://github.com/iakunin/codexia-bot/issues/23), [#24](https://github.com/iakunin/codexia-bot/issues/24), [#25](https://github.com/iakunin/codexia-bot/issues/25), [#26](https://github.com/iakunin/codexia-bot/issues/26).
