### ISSUE TITLE
Refactor `FoundOnHackernews` & `FoundOnReddit` to get rid of duplication

### ISSUE THREAD

**Issue by iakunin** [iakunin/codexia-bot#66]

**Comment by 0pdd** [comment]
@iakunin 2 puzzles [#74](https://github.com/iakunin/codexia-bot/issues/74), [#75](https://github.com/iakunin/codexia-bot/issues/75) are still not solved.

**Comment by 0pdd** [comment]
@iakunin 3 puzzles [#167](https://github.com/iakunin/codexia-bot/issues/167), [#168](https://github.com/iakunin/codexia-bot/issues/168), [#75](https://github.com/iakunin/codexia-bot/issues/75) are still not solved; solved: [#74](https://github.com/iakunin/codexia-bot/issues/74).

**Comment by 0pdd** [comment]
@iakunin 2 puzzles [#167](https://github.com/iakunin/codexia-bot/issues/167), [#168](https://github.com/iakunin/codexia-bot/issues/168) are still not solved; solved: [#74](https://github.com/iakunin/codexia-bot/issues/74), [#75](https://github.com/iakunin/codexia-bot/issues/75).

**Comment by 0pdd** [comment]
@iakunin all 4 puzzles are solved here: [#167](https://github.com/iakunin/codexia-bot/issues/167), [#168](https://github.com/iakunin/codexia-bot/issues/168), [#74](https://github.com/iakunin/codexia-bot/issues/74), [#75](https://github.com/iakunin/codexia-bot/issues/75).
