### ISSUE TITLE
Implement `too-small` bot

### ISSUE THREAD

**Issue by iakunin** [iakunin/codexia-bot#92]
* report when the size of the repo is smaller than the threshold
* report text `The repo is too small (LoC is 123)`
* set meta marker once reported
* don't report anymore, while the meta marker is present
* report and remove the marker if the size of the repo is above the threshold
* report text `The repo is not small anymore (LoC is 456)`
* the threshold is 5K LoC

-----

- [x] implement the bot
- [x] cover by tests
- [x] append project README

**Comment by 0pdd** [comment]
@iakunin 5 puzzles [#130](https://github.com/iakunin/codexia-bot/issues/130), [#131](https://github.com/iakunin/codexia-bot/issues/131), [#132](https://github.com/iakunin/codexia-bot/issues/132), [#133](https://github.com/iakunin/codexia-bot/issues/133), [#134](https://github.com/iakunin/codexia-bot/issues/134) are still not solved.

**Comment by iakunin** [comment]
Done

**Comment by 0pdd** [comment]
@iakunin 4 puzzles [#130](https://github.com/iakunin/codexia-bot/issues/130), [#131](https://github.com/iakunin/codexia-bot/issues/131), [#132](https://github.com/iakunin/codexia-bot/issues/132), [#134](https://github.com/iakunin/codexia-bot/issues/134) are still not solved; solved: [#133](https://github.com/iakunin/codexia-bot/issues/133).

**Comment by 0pdd** [comment]
@iakunin 3 puzzles [#131](https://github.com/iakunin/codexia-bot/issues/131), [#132](https://github.com/iakunin/codexia-bot/issues/132), [#134](https://github.com/iakunin/codexia-bot/issues/134) are still not solved; solved: [#130](https://github.com/iakunin/codexia-bot/issues/130), [#133](https://github.com/iakunin/codexia-bot/issues/133).

**Comment by 0pdd** [comment]
@iakunin the puzzle [#134](https://github.com/iakunin/codexia-bot/issues/134) is still not solved; solved: [#130](https://github.com/iakunin/codexia-bot/issues/130), [#131](https://github.com/iakunin/codexia-bot/issues/131), [#132](https://github.com/iakunin/codexia-bot/issues/132), [#133](https://github.com/iakunin/codexia-bot/issues/133).

**Comment by 0pdd** [comment]
@iakunin all 5 puzzles are solved here: [#130](https://github.com/iakunin/codexia-bot/issues/130), [#131](https://github.com/iakunin/codexia-bot/issues/131), [#132](https://github.com/iakunin/codexia-bot/issues/132), [#133](https://github.com/iakunin/codexia-bot/issues/133), [#134](https://github.com/iakunin/codexia-bot/issues/134).
